#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes

h=1
m=1
while (("$h" < 13))
do
    echo "Hour: $h"
    ((m = 1))
    while (("$m" < 60))
    do
        echo "$m"
        ((m += 1))
    done
    ((h += 1))
done
